name: deploy-dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build
        env:
          CI: false
          REACT_APP_API: ${{ secrets.APIURL_DEV }}
          REACT_APP_URL: https://app.dev.linpe.com.br
          REACT_APP_GOOGLEGA: ${{ secrets.GOOGLEGA_DEV }}
        run: yarn install && yarn build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.BUCKET_DEV }} --delete
